######################################################################
# Automatically generated by qmake (3.0) tis mar 31 20:15:58 2015
######################################################################

TEMPLATE = app
TARGET = maze-game
QT += core gui
QT += widgets
#INCLUDEPATH += .

# Input
SOURCES += src/main.cpp
SOURCES += src/ConfigParser.cpp
SOURCES += src/MazeManager.cpp